export const I3 = [
  {
    name: "BDA",
    time: "8:30am-9:30am",
    faculty: "MS",
    day: "Monday",
  },
  {
    name: "IPCV Laboratory",
    time: "09:30am-11:30am",
    faculty: "NK",
    day: "Monday",
  },
  {
    name: "FSD",
    time: "9:30am-11:30am",
    faculty: "SP",
    day: "Monday",
  },
  {
    name: "BDA Laboratory",
    time: "12:00pm-2:00pm",
    faculty: "MS",
    day: "Monday",
  },
  {
    name: "ARVR Laboratory",
    time: "12:00pm-2:00pm",
    faculty: "PS",
    day: "Monday",
  },
  {
    name: "IS Laboratory",
    time: "12:00pm-2:00pm",
    faculty: "AP",
    day: "Monday",
  },
  ,
  {
    name: "ARVR",
    time: "2:00pm-3:00pm",
    faculty: "PS",
    day: "Monday",
  },
  {
    name: "IS",
    time: "2:00pm-3:00pm",
    faculty: "AP",
    day: "Monday",
  },

  {
    name: "ML Laboratory",
    time: "10:00am-12:00pm",
    faculty: "PG",
    day: "Tuesday",
  },
  {
    name: "IPCV Laboratory",
    time: "10:00am-12:00pm",
    faculty: "NK",
    day: "Tuesday",
  },
  {
    name: "BDA",
    time: "12:00pm-1:00pm",
    faculty: "MS",
    day: "Tuesday",
  },
  {
    name: "ML",
    time: "1:30pm-2:30pm",
    faculty: "PG",
    day: "Tuesday",
  },
  {
    name: "ISIG",
    time: "2:30pm-3:30pm",
    faculty: "RM",
    day: "Tuesday",
  },
  {
    name: "ISIG Laboratory",
    time: "3:30pm-5:30pm",
    faculty: "CB",
    day: "Tuesday",
  },

  {
    name: "ISIG Laboratory",
    time: "8:00am-10:00am",
    faculty: "RM",
    day: "Wednesday",
  },
  {
    name: "SE Laboratory",
    time: "8:00am-10:00am",
    faculty: "HD",
    day: "Wednesday",
  },
  {
    name: "ML",
    time: "10:00am-11:00am",
    faculty: "PG",
    day: "Wednesday",
  },
  {
    name: "BDA",
    time: "11:00am-12:00pm",
    faculty: "MS",
    day: "Wednesday",
  },
  {
    name: "SE",
    time: "12:30pm-1:30pm",
    faculty: "RS",
    day: "Wednesday",
  },
  {
    name: "IPCV",
    time: "1:30pm-2:30pm",
    faculty: "NK",
    day: "Wednesday",
  },
  {
    name: "ARVR",
    time: "2:30pm-3:30pm",
    faculty: "PS",
    day: "Wednesday",
  },
  {
    name: "IS",
    time: "2:30pm-3:30pm",
    faculty: "AP",
    day: "Wednesday",
  },
  {
    name: "ISIG",
    time: "2:30pm-3:30pm",
    faculty: "RM",
    day: "Wednesday",
  },
  {
    name: "Minors",
    time: "3:30pm-5:30pm",
    faculty: "CB",
    day: "Wednesday",
  },
  {
    name: "Honors",
    time: "3:30pm-5:30pm",
    faculty: "MS",
    day: "Wednesday",
  },
  {
    name: "SE Laboratory",
    time: "8:00am-10:00am",
    faculty: "HD",
    day: "Thursday",
  },
  {
    name: "BDA Laboratory",
    time: "8:00am-10:00am",
    faculty: "MS",
    day: "Thursday",
  },
  {
    name: "FSD Laboratory",
    time: "10:00am-12:00pm",
    faculty: "NA",
    day: "Thursday",
  },
  {
    name: "ML Laboratory",
    time: "10:00am-12:00pm",
    faculty: "PG",
    day: "Thursday",
  },
  {
    name: "IPCV",
    time: "12:30pm-1:30pm",
    faculty: "NK",
    day: "Thursday",
  },
  {
    name: "Honors",
    time: "3:30pm-5:30pm",
    faculty: "AJ",
    day: "Thursday",
  },

  {
    name: "Honors Laboratory (LS)",
    time: "8:00am-10:00am",
    faculty: "LS",
    day: "Friday",
  },
  {
    name: "SE",
    time: "10:00am-11:00am",
    faculty: "HD",
    day: "Friday",
  },
  {
    name: "SE",
    time: "11:00am-12:00pm",
    faculty: "HD",
    day: "Friday",
  },
  {
    name: "ML",
    time: "12:30pm-1:30pm",
    faculty: "PG",
    day: "Friday",
  },
  {
    name: "IPCV",
    time: "1:30pm-2:30pm",
    faculty: "NK",
    day: "Friday",
  },

  {
    name: "ARVR",
    time: "2:30pm-3:30pm",
    faculty: "PS",
    day: "Friday",
  },
  {
    name: "IS",
    time: "2:30pm-3:30pm",
    faculty: "AP",
    day: "Friday",
  },
  {
    name: "ISIG",
    time: "2:30pm-3:30pm",
    faculty: "RM",
    day: "Friday",
  },
  {
    name: "Minors Laboratory",
    time: "3:30pm-5:30pm",
    faculty: "CB",
    day: "Friday",
  },
  {
    name: "Honors Laboratory (SSP)",
    time: "3:30pm-5:30pm",
    faculty: "SSP",
    day: "Friday",
  },

  {
    name: "Minors",
    time: "3:30pm-5:30pm",
    faculty: "CB",
    day: "Saturday",
  },
].map((classItem, index) => ({ ...classItem, id: index + 1 }));
